=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end
	
def fibonacci(n)
	a, b = 1, 2
	while b < n do
		a, b = b, b+a
		(results ||= []) << b
	end
	results
end
sum = 0
fibonacci( 4e6 ).each do |i|
	sum += i if i%2 == 0
end

puts sum





